import { chmod, copyFile, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { globalSkillDir, type PathEnv, projectSkillDir, SKILL_NAME } from "../config/paths.js";
import { dirExists, fileExists, readJson, writeJson } from "../util/fs.js";

export type InstallScope = "global" | "project";

export const SKILL_MANIFEST_NAME = ".jev-orchestrator.json";
export const HELPER_SCRIPT_NAME = "jev-orchestrator";
const SKILL_FILE = "SKILL.md";
const REFERENCES_DIR = "references";
const SCRIPTS_DIR = "scripts";
const MODE_EXECUTABLE = 0o755;

export interface SkillManifest {
  version: string;
  scope: InstallScope;
  installedAt: string;
  /** Absolute path to the CLI entry the helper script runs. */
  cliEntry: string;
  skillDir: string;
}

export interface InstallOptions {
  scope: InstallScope;
  /** Required for project scope. */
  projectRoot?: string;
  /** Directory containing SKILL.md and references/ (the package's skill/ folder). */
  sourceDir: string;
  cliEntry: string;
  version: string;
  env?: PathEnv;
}

export interface InstallResult {
  skillDir: string;
  skillFile: string;
  helperScript: string;
  updated: boolean;
}

export function resolveSkillDir(
  scope: InstallScope,
  projectRoot: string | undefined,
  env: PathEnv = process.env,
): string {
  if (scope === "global") {
    return globalSkillDir(env);
  }
  if (!projectRoot) {
    throw new Error("projectRoot is required for project-scoped installation.");
  }
  return projectSkillDir(projectRoot);
}

const REINSTALL_HINT =
  "jev-orchestrator CLI not found at the recorded path. Reinstall with: npx jev-orchestrator install --scope <global|project>";

/**
 * POSIX shim that runs the exact CLI which installed the skill. It never
 * downloads code: when the CLI moved or was removed, it fails with a
 * reinstall hint rather than pulling a package from the network under the
 * pre-approved permission rule. Paths are quoted so spaces work.
 */
export function helperScript(cliEntry: string): string {
  const quoted = cliEntry.replace(/"/g, '\\"');
  return [
    "#!/usr/bin/env sh",
    "# Generated by jev-orchestrator. Runs the CLI that installed this skill.",
    `CLI="${quoted}"`,
    'if [ ! -f "$CLI" ]; then',
    `  echo "${REINSTALL_HINT}" >&2`,
    "  exit 1",
    "fi",
    'exec node "$CLI" "$@"',
    "",
  ].join("\n");
}

export function helperScriptWindows(cliEntry: string): string {
  return [
    "@echo off",
    `if not exist "${cliEntry}" (`,
    `  echo ${REINSTALL_HINT} 1>&2`,
    "  exit /b 1",
    ")",
    `node "${cliEntry}" %*`,
    "",
  ].join("\r\n");
}

export async function readSkillManifest(skillDir: string): Promise<SkillManifest | undefined> {
  return readJson<SkillManifest>(join(skillDir, SKILL_MANIFEST_NAME));
}

/**
 * Copies SKILL.md verbatim (Claude Code substitutes `${CLAUDE_SKILL_DIR}` itself,
 * in the body and in `allowed-tools`), the references, and writes the helper shim.
 */
export async function installSkill(options: InstallOptions): Promise<InstallResult> {
  const env = options.env ?? process.env;
  const skillDir = resolveSkillDir(options.scope, options.projectRoot, env);
  const existing = await readSkillManifest(skillDir);

  await Promise.all([
    mkdir(join(skillDir, REFERENCES_DIR), { recursive: true }),
    mkdir(join(skillDir, SCRIPTS_DIR), { recursive: true }),
  ]);

  const skillFile = join(skillDir, SKILL_FILE);
  const refSource = join(options.sourceDir, REFERENCES_DIR);
  const refs = (await readdir(refSource)).filter((name) => name.endsWith(".md"));
  await Promise.all([
    copyFile(join(options.sourceDir, SKILL_FILE), skillFile),
    ...refs.map((name) => copyFile(join(refSource, name), join(skillDir, REFERENCES_DIR, name))),
  ]);

  const helper = join(skillDir, SCRIPTS_DIR, HELPER_SCRIPT_NAME);
  await writeFile(helper, helperScript(options.cliEntry), {
    encoding: "utf8",
    mode: MODE_EXECUTABLE,
  });
  await chmod(helper, MODE_EXECUTABLE);
  await writeFile(`${helper}.cmd`, helperScriptWindows(options.cliEntry), "utf8");

  const manifest: SkillManifest = {
    version: options.version,
    scope: options.scope,
    installedAt: new Date().toISOString(),
    cliEntry: options.cliEntry,
    skillDir,
  };
  await writeJson(join(skillDir, SKILL_MANIFEST_NAME), manifest);

  return { skillDir, skillFile, helperScript: helper, updated: existing !== undefined };
}

export interface UninstallResult {
  skillDir: string;
  removed: boolean;
  reason?: string;
}

/** Removes only a directory that carries our manifest. */
export async function uninstallSkill(
  scope: InstallScope,
  projectRoot: string | undefined,
  env: PathEnv = process.env,
): Promise<UninstallResult> {
  const skillDir = resolveSkillDir(scope, projectRoot, env);
  if (!(await dirExists(skillDir))) {
    return { skillDir, removed: false, reason: "not installed" };
  }
  const manifest = await readSkillManifest(skillDir);
  if (!manifest) {
    return {
      skillDir,
      removed: false,
      reason: `${skillDir} has no ${SKILL_MANIFEST_NAME}; it was not installed by jev-orchestrator. Remove it manually if intended.`,
    };
  }
  await rm(skillDir, { recursive: true, force: true });
  return { skillDir, removed: true };
}

export interface Installation {
  scope: InstallScope;
  skillDir: string;
  manifest?: SkillManifest;
  skillFilePresent: boolean;
  helperPresent: boolean;
}

export async function detectInstallations(
  projectRoot: string | undefined,
  env: PathEnv = process.env,
): Promise<Installation[]> {
  const candidates: { scope: InstallScope; dir: string }[] = [
    { scope: "global", dir: globalSkillDir(env) },
  ];
  if (projectRoot) {
    candidates.push({ scope: "project", dir: projectSkillDir(projectRoot) });
  }
  const out: Installation[] = [];
  for (const c of candidates) {
    const skillFilePresent = await fileExists(join(c.dir, SKILL_FILE));
    if (!skillFilePresent) {
      continue;
    }
    const manifest = await readSkillManifest(c.dir);
    out.push({
      scope: c.scope,
      skillDir: c.dir,
      ...(manifest ? { manifest } : {}),
      skillFilePresent,
      helperPresent: await fileExists(join(c.dir, SCRIPTS_DIR, HELPER_SCRIPT_NAME)),
    });
  }
  return out;
}

export { SKILL_NAME };
